name: mycarclub
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #image
  flutter_svg: ^1.0.0
  mj_image_slider: ^0.0.7
  cached_network_image: ^3.2.3
  flick_video_player: ^0.5.0
  video_player: ^2.6.1
  vimeo_video_player: ^0.0.6

  #default
  cupertino_icons: ^1.0.2

  #Utilities
  http: ^0.13.5
  qr_flutter: ^4.0.0
  awesome_dialog: ^3.0.2
  dropdown_search: ^5.0.6
  flutter_animation_progress_bar: ^2.3.1
  url_launcher: ^6.1.10
  intl: ^0.18.0
  flutter_timezone: ^1.0.4
  page_transition: ^2.0.9
  flutter_color_utils: ^0.0.1
  chat_bubbles: ^1.4.1
  animated_tree_view: ^1.1.1+1
  custom_clippers: ^2.0.0
  google_fonts: ^4.0.4
  visibility_detector: ^0.4.0+2
  pin_input_text_field: ^4.5.0
  pull_to_refresh: ^2.0.0
  carousel_slider: ^4.2.1
  coupon_uikit: ^0.2.0
  smooth_page_indicator: ^1.1.0
  sticky_headers: ^0.3.0+2
  syncfusion_flutter_charts: ^20.4.51
  graphview: ^1.2.0
  flutter_html_all: ^3.0.0-beta.2
#  rate_my_app: ^1.1.4

  #State Management
  provider: ^6.0.5
  get: ^4.6.5

  #  Backend
  api_cache_manager: ^1.0.2
  get_it: ^7.2.0
  # dio: ^4.0.6
  sqflite: ^2.2.6
  shared_preferences: ^2.1.0
  firebase_core: ^2.0.0
  cloud_firestore: ^4.5.3
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^13.0.0

#  power_file_view: ^1.0.1
  path_provider: ^2.0.14
  liquid_progress_indicator: ^0.4.0
  intl_phone_field: ^3.1.0
  connectivity_plus: ^3.0.4
  fluttertoast: ^8.2.1
  #  toast: ^0.1.5
  #  Animations
  rive: ^0.9.1
  cherry_toast: ^1.2.0
  lottie: ^2.3.2
  circular_progress_bar_with_lines: ^0.0.7
  action_slider: ^0.6.1
  #  cache
  flutter_cache_manager: ^3.3.0
  #  device
  package_info_plus: ^3.1.2
  local_auth: ^2.1.6
  device_info_plus: ^8.2.2
  flutter_rating_bar: ^4.0.1
  envied: ^0.3.0+3
  flutter_branch_sdk: ^6.6.0
  share_plus: ^6.3.4
  uni_links: ^0.5.1
  ansicolor: ^2.0.1
  timelines: ^0.1.0
  in_app_review: ^2.0.6
  flutter_app_badger: ^1.5.0
  simple_gradient_text: ^1.2.4
  # youtube_player_flutter: ^8.1.2
  youtube_explode_dart: ^1.12.4
  pod_player: ^0.1.4
  audio_video_progress_bar: ^1.0.1
  slide_countdown: ^0.6.0
  flutter_flip_card: ^0.0.4
  flutter_spinkit: ^5.2.0
  flutter_custom_clippers: ^2.1.0
  dio: ^5.3.3
  flutter_rounded_date_picker: ^3.0.4
  toggle_switch: ^2.1.0
  flutter_breadcrumb: ^1.0.1
  loadmore: ^2.1.0
  swipeable_tile: ^2.0.0+3
  banner_carousel: ^1.2.1
  flutter_fancy_tree_view: ^1.1.1
  path_drawing: ^1.0.1
  version: ^3.0.2
  os_detect: ^2.0.1
  pdf: ^3.10.1
  printing: ^5.10.4
  open_file: ^3.3.2
  floating_chat_button: ^1.0.1
  percent_indicator: ^4.2.3
  activity_ring: ^0.3.0
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^4.0.4
  html: ^0.15.4
  auto_size_text: ^3.0.0
  firebase_crashlytics: ^3.4.1
  logger: ^2.0.2+1
  in_app_purchase: ^3.1.11
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  flutter_upgrade_version: ^1.1.1





  #  flutter_firebase_recaptcha: ^1.0.2
  #  webview_flutter_plus: ^0.3.0+2
  #  flutter_scroll_to_top: ^2.3.0
  #  gradient_slide_to_act: ^0.0.2
  #  flutter_app_version_checker: ^0.3.2
  #  molten_navigationbar_flutter: ^1.0.1
  #  flutter_cached_pdfview: ^0.4.1
  #  flutter_webview_plugin: ^0.4.0
  #  syncfusion_flutter_pdfviewer: ^21.1.41
  #  app_updater: ^1.0.4




#dependency_overrides:
#  firebase_core_platform_interface: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"
  change_app_package_name: ^1.1.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appLogo_s.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/designs/
    - assets/svg/
    - assets/images/
    - assets/images/card_images/
    - assets/videos/
    - assets/rive/
    - assets/lottie/
    - icons/

  fonts:
    - family: halter
      fonts:
        - asset: font/halter.ttf